import {
  Activity,
  BarChart3,
  BadgeCheck,
  Briefcase,
  Blocks,
  Brain,
  Bug,
  Code2,
  Compass,
  Cpu,
  LayoutDashboard,
  LineChart,
  MousePointerClick,
  Radio,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Target,
  TrendingUp,
  Users,
  Workflow,
} from 'lucide-react';

export const SERVICE_ICON_OPTIONS = [
  { value: 'seo', label: 'SEO', icon: Search },
  { value: 'cro', label: 'CRO & Testes A/B', icon: MousePointerClick },
  { value: 'analytics', label: 'Digital Analytics', icon: BarChart3 },
  { value: 'development', label: 'Desenvolvimento', icon: Code2 },
  { value: 'strategy', label: 'Estratégia', icon: Brain },
  { value: 'automation', label: 'Automação', icon: Workflow },
  { value: 'dashboards', label: 'Dashboards', icon: LayoutDashboard },
  { value: 'data-quality', label: 'Qualidade de dados', icon: BadgeCheck },
  { value: 'tracking', label: 'Tagueamento', icon: ShieldCheck },
  { value: 'performance', label: 'Performance', icon: LineChart },
  { value: 'ops', label: 'Operações', icon: Blocks },
  { value: 'engineering', label: 'Engenharia', icon: Cpu },
  { value: 'testing', label: 'Testes', icon: Bug },
  { value: 'growth', label: 'Growth', icon: Rocket },
  { value: 'signal', label: 'Sinal & Métrica', icon: Activity },
  { value: 'compass', label: 'Bússola', icon: Compass },
  { value: 'target', label: 'Alvo', icon: Target },
  { value: 'radio', label: 'Sinal de rádio', icon: Radio },
  { value: 'users', label: 'Pessoas', icon: Users },
  { value: 'briefcase', label: 'Maleta', icon: Briefcase },
  { value: 'trending-up', label: 'Tendência de alta', icon: TrendingUp },
] as const;

export const getServiceIcon = (iconName?: string) => {
  return SERVICE_ICON_OPTIONS.find((option) => option.value === iconName)?.icon || Sparkles;
};
