# Generated by Django 6.1.1 on 2026-09-24 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('recipient_email', models.EmailField(blank=True, help_text='Quem recebe as mensagens do formulário.', max_length=254, verbose_name='destinatário')),
                ('sender_email', models.EmailField(blank=True, help_text='Precisa ser um remetente verificado no SendGrid.', max_length=254, verbose_name='remetente')),
                ('sender_name', models.CharField(blank=True, max_length=120, verbose_name='nome do remetente')),
            ],
            options={
                'verbose_name': 'envio do formulário de contato',
                'verbose_name_plural': 'envio do formulário de contato',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('email', models.EmailField(max_length=255, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='página de origem')),
                ('source_context', models.CharField(blank=True, max_length=120, verbose_name='contexto de origem')),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='queued', max_length=10, verbose_name='status do envio')),
                ('email_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID da mensagem no SendGrid')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='dados recebidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='página de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='página de origem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inscrito em')),
            ],
            options={
                'verbose_name': 'inscrito na newsletter',
                'verbose_name_plural': 'inscritos na newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+(\\.[a-z0-9_]+)*$', 'Use o formato secao.campo (minúsculas, números, _ e .).')], verbose_name='chave')),
                ('value', models.TextField(blank=True, verbose_name='valor')),
                ('description', models.CharField(blank=True, help_text='O que é e onde aparece.', max_length=255, verbose_name='descrição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'opção do site',
                'verbose_name_plural': 'opções do site',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=500, verbose_name='página')),
                ('button_context', models.CharField(max_length=120, verbose_name='botão')),
                ('target_number', models.CharField(blank=True, max_length=30, verbose_name='número')),
                ('message_text', models.TextField(blank=True, verbose_name='mensagem')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='clicado em')),
            ],
            options={
                'verbose_name': 'clique no WhatsApp',
                'verbose_name_plural': 'cliques no WhatsApp',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(blank=True, help_text='Só dígitos, com DDI. Ex.: 5511999999999', max_length=30, verbose_name='número')),
                ('enabled', models.BooleanField(default=True, verbose_name='botão ativo')),
                ('message', models.TextField(blank=True, verbose_name='mensagem inicial')),
            ],
            options={
                'verbose_name': 'WhatsApp',
                'verbose_name_plural': 'WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(help_text='Endereço: /cases/<slug>', max_length=255, unique=True, verbose_name='slug')),
                ('tag', models.CharField(max_length=120, verbose_name='tag')),
                ('excerpt', models.TextField(verbose_name='resumo')),
                ('kpi_value', models.CharField(help_text='Ex.: "+40%"', max_length=60, verbose_name='KPI — valor')),
                ('kpi_label', models.CharField(help_text='Ex.: "conversão"', max_length=120, verbose_name='KPI — rótulo')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='cliente')),
                ('service_stack', models.CharField(blank=True, max_length=255, verbose_name='escopo')),
                ('featured_image', models.ImageField(upload_to='cases/', verbose_name='imagem de destaque')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo da imagem')),
                ('content_html', models.TextField(help_text='HTML. Imagens são referenciadas por <img data-image-id="ID"> (ID de uma Imagem de conteúdo).', verbose_name='conteúdo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'case',
                'verbose_name_plural': 'cases',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('logo', models.ImageField(blank=True, upload_to='companies/', verbose_name='logo')),
                ('logo_alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo do logo')),
                ('website_url', models.URLField(blank=True, verbose_name='site')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(help_text='Ex.: "São Paulo"', max_length=120, verbose_name='rótulo')),
                ('street', models.CharField(max_length=255, verbose_name='logradouro e número')),
                ('complement', models.CharField(blank=True, max_length=120, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('city', models.CharField(max_length=120, verbose_name='cidade')),
                ('state', models.CharField(max_length=60, verbose_name='estado')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='CEP / ZIP')),
                ('country', models.CharField(max_length=60, verbose_name='país')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('hours', models.CharField(blank=True, max_length=120, verbose_name='horário')),
                ('map_url', models.URLField(blank=True, max_length=500, verbose_name='mapa (URL de incorporação)')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content/', verbose_name='imagem')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
            ],
            options={
                'verbose_name': 'imagem de conteúdo',
                'verbose_name_plural': 'imagens de conteúdo',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(help_text='Endereço: /servicos/<slug>', max_length=255, unique=True, verbose_name='slug')),
                ('icon_name', models.CharField(choices=[('seo', 'SEO'), ('cro', 'CRO & Testes A/B'), ('analytics', 'Digital Analytics'), ('development', 'Desenvolvimento'), ('strategy', 'Estratégia'), ('automation', 'Automação'), ('dashboards', 'Dashboards'), ('data-quality', 'Qualidade de dados'), ('tracking', 'Tagueamento'), ('performance', 'Performance'), ('ops', 'Operações'), ('engineering', 'Engenharia'), ('testing', 'Testes'), ('growth', 'Growth'), ('signal', 'Sinal & Métrica')], max_length=40, verbose_name='ícone')),
                ('excerpt', models.TextField(verbose_name='resumo')),
                ('content_html', models.TextField(help_text='HTML. Imagens são referenciadas por <img data-image-id="ID"> (ID de uma Imagem de conteúdo).', verbose_name='conteúdo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('role', models.CharField(max_length=255, verbose_name='cargo')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='foto')),
                ('photo_alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo da foto')),
                ('show_on_home', models.BooleanField(default=True, help_text='Seção Time da home.', verbose_name='aparece na home')),
                ('show_on_about', models.BooleanField(default=False, help_text='Seção "Heads da operação" do Quem Somos.', verbose_name='aparece no Quem Somos')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'membro do time',
                'verbose_name_plural': 'time',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('role', models.CharField(max_length=255, verbose_name='cargo')),
                ('company', models.CharField(max_length=255, verbose_name='empresa')),
                ('text', models.TextField(verbose_name='depoimento')),
                ('show_in_client_panel', models.BooleanField(default=False, help_text='Carrossel laranja "// Cliente" da home.', verbose_name='aparece no painel Cliente')),
                ('show_in_testimonials', models.BooleanField(default=True, help_text='Seção Depoimentos da home.', verbose_name='aparece em Depoimentos')),
                ('show_on_about', models.BooleanField(default=False, help_text='O Quem Somos mostra um depoimento só: o primeiro marcado, por posição.', verbose_name='destaque do Quem Somos')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'depoimento',
                'verbose_name_plural': 'depoimentos',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
    ]
