# Generated by Django 6.1.1 on 2026-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='content_html',
            field=models.TextField(help_text='HTML. Imagens são referenciadas por <img data-image-id="ID"> (ID de uma Imagem de conteúdo). Scripts, estilos e atributos fora da lista permitida são removidos ao salvar.', verbose_name='conteúdo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content_html',
            field=models.TextField(help_text='HTML. Imagens são referenciadas por <img data-image-id="ID"> (ID de uma Imagem de conteúdo). Scripts, estilos e atributos fora da lista permitida são removidos ao salvar.', verbose_name='conteúdo'),
        ),
    ]
