# Generated by Django 6.1.1 on 2026-09-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rich_text_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='altura'),
        ),
        migrations.AddField(
            model_name='contentimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='largura'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='content/', verbose_name='imagem', width_field='width'),
        ),
    ]
