# Generated by Django 6.1.1 on 2026-09-24 21:09

import content.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_image_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('mini_bio', models.TextField(blank=True, verbose_name='minibio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'autor',
                'verbose_name_plural': 'autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+(\\.[a-z0-9_]+)*$', 'Use o formato secao.campo (minúsculas, números, _ e .).')], verbose_name='chave')),
                ('image', models.ImageField(upload_to='site/', verbose_name='imagem')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo')),
                ('description', models.CharField(blank=True, help_text='O que é e onde aparece.', max_length=255, verbose_name='descrição')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'imagem do site',
                'verbose_name_plural': 'imagens do site',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='siteoption',
            name='label',
            field=models.CharField(blank=True, help_text='Texto que acompanha o valor (ex.: "Receita orgânica média").', max_length=255, verbose_name='rótulo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_name',
            field=models.CharField(choices=[('seo', 'SEO'), ('cro', 'CRO & Testes A/B'), ('analytics', 'Digital Analytics'), ('development', 'Desenvolvimento'), ('strategy', 'Estratégia'), ('automation', 'Automação'), ('dashboards', 'Dashboards'), ('data-quality', 'Qualidade de dados'), ('tracking', 'Tagueamento'), ('performance', 'Performance'), ('ops', 'Operações'), ('engineering', 'Engenharia'), ('testing', 'Testes'), ('growth', 'Growth'), ('signal', 'Sinal & Métrica'), ('compass', 'Bússola'), ('target', 'Alvo'), ('radio', 'Sinal de rádio'), ('users', 'Pessoas'), ('briefcase', 'Maleta'), ('trending-up', 'Tendência de alta')], max_length=40, verbose_name='ícone'),
        ),
        migrations.AlterField(
            model_name='siteoption',
            name='value',
            field=models.TextField(blank=True, help_text='Texto: *asteriscos* marcam o destaque (laranja/itálico) e Enter quebra a linha. Números: só o número (ex.: 312).', verbose_name='valor'),
        ),
        migrations.CreateModel(
            name='AboutHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'diferencial do Quem Somos',
                'verbose_name_plural': 'diferenciais do Quem Somos',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tag', models.CharField(max_length=60, verbose_name='tag')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('image', models.ImageField(upload_to='about/', verbose_name='imagem')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo da imagem')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'pilar do Quem Somos',
                'verbose_name_plural': 'pilares do Quem Somos',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(max_length=80, verbose_name='rótulo')),
                ('icon_name', models.CharField(choices=[('seo', 'SEO'), ('cro', 'CRO & Testes A/B'), ('analytics', 'Digital Analytics'), ('development', 'Desenvolvimento'), ('strategy', 'Estratégia'), ('automation', 'Automação'), ('dashboards', 'Dashboards'), ('data-quality', 'Qualidade de dados'), ('tracking', 'Tagueamento'), ('performance', 'Performance'), ('ops', 'Operações'), ('engineering', 'Engenharia'), ('testing', 'Testes'), ('growth', 'Growth'), ('signal', 'Sinal & Métrica'), ('compass', 'Bússola'), ('target', 'Alvo'), ('radio', 'Sinal de rádio'), ('users', 'Pessoas'), ('briefcase', 'Maleta'), ('trending-up', 'Tendência de alta')], max_length=40, verbose_name='ícone')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'capacidade',
                'verbose_name_plural': 'capacidades',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('icon_name', models.CharField(choices=[('seo', 'SEO'), ('cro', 'CRO & Testes A/B'), ('analytics', 'Digital Analytics'), ('development', 'Desenvolvimento'), ('strategy', 'Estratégia'), ('automation', 'Automação'), ('dashboards', 'Dashboards'), ('data-quality', 'Qualidade de dados'), ('tracking', 'Tagueamento'), ('performance', 'Performance'), ('ops', 'Operações'), ('engineering', 'Engenharia'), ('testing', 'Testes'), ('growth', 'Growth'), ('signal', 'Sinal & Métrica'), ('compass', 'Bússola'), ('target', 'Alvo'), ('radio', 'Sinal de rádio'), ('users', 'Pessoas'), ('briefcase', 'Maleta'), ('trending-up', 'Tendência de alta')], max_length=40, verbose_name='ícone')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'modelo de contratação',
                'verbose_name_plural': 'modelos de contratação',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('icon_name', models.CharField(choices=[('seo', 'SEO'), ('cro', 'CRO & Testes A/B'), ('analytics', 'Digital Analytics'), ('development', 'Desenvolvimento'), ('strategy', 'Estratégia'), ('automation', 'Automação'), ('dashboards', 'Dashboards'), ('data-quality', 'Qualidade de dados'), ('tracking', 'Tagueamento'), ('performance', 'Performance'), ('ops', 'Operações'), ('engineering', 'Engenharia'), ('testing', 'Testes'), ('growth', 'Growth'), ('signal', 'Sinal & Métrica'), ('compass', 'Bússola'), ('target', 'Alvo'), ('radio', 'Sinal de rádio'), ('users', 'Pessoas'), ('briefcase', 'Maleta'), ('trending-up', 'Tendência de alta')], max_length=40, verbose_name='ícone')),
                ('tags', models.CharField(blank=True, help_text='Separe com vírgula. Ex.: Stack audit, Data quality', max_length=255, verbose_name='tags')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'passo do método',
                'verbose_name_plural': 'passos do método',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.IntegerField(default=0, help_text='Menor aparece primeiro.', verbose_name='posição')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(max_length=60, verbose_name='rótulo')),
                ('url', models.CharField(help_text='URL completa ou caminho do site (ex.: /privacidade).', max_length=500, verbose_name='link')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'link do rodapé',
                'verbose_name_plural': 'links do rodapé',
                'ordering': ['order_position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('slug', models.SlugField(help_text='Endereço: /blog/<slug>', max_length=255, unique=True, verbose_name='slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='subtítulo')),
                ('featured_image', models.ImageField(upload_to='blog/', verbose_name='imagem principal')),
                ('featured_image_alt', models.CharField(blank=True, max_length=255, verbose_name='texto alternativo da imagem')),
                ('content_html', models.TextField(help_text='HTML. Imagens são referenciadas por <img data-image-id="ID"> (ID de uma Imagem de conteúdo). Scripts, estilos e atributos fora da lista permitida são removidos ao salvar.', verbose_name='conteúdo')),
                ('published_at', models.DateField(verbose_name='data de publicação')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarcado = não aparece no site.', verbose_name='publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.author', verbose_name='autor')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='content.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-published_at', '-created_at'],
            },
            bases=(content.models.SanitizedContentMixin, models.Model),
        ),
    ]
