# Generated by Django 6.1.1 on 2026-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_site_content_and_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notified_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Preenchido pelo resumo por e-mail (send_contact_digest). Vazio = ainda não enviado.', null=True, verbose_name='enviado no resumo em'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='notified_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Preenchido pelo resumo por e-mail (send_contact_digest). Vazio = ainda não enviado.', null=True, verbose_name='enviado no resumo em'),
        ),
    ]
