# Generated by Django 6.1.1 on 2026-09-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_digest_notified_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSettings',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='email_message_id',
        ),
    ]
