# Generated by Django 6.1.1 on 2026-09-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_contact_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capability',
        ),
    ]
